---
apiVersion: v1
kind: Service
metadata:
  name: dataaccess
  labels:
    name: dataaccess
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: dataaccess
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataaccess
spec:
  selector:
    matchLabels:
      app: dataaccess
  replicas: 1
  template:
    metadata:
      labels:
        app: dataaccess
    spec:
      containers:
        - name: dataaccess
          image: ankita1793/dataaccess:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password